// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: gateway/v1/gateway.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayAdminService_GetRouteSnapshot_FullMethodName  = "/gateway.v1.GatewayAdminService/GetRouteSnapshot"
	GatewayAdminService_ReloadRoutes_FullMethodName      = "/gateway.v1.GatewayAdminService/ReloadRoutes"
	GatewayAdminService_GetUpstreamHealth_FullMethodName = "/gateway.v1.GatewayAdminService/GetUpstreamHealth"
	GatewayAdminService_GetGatewayVersion_FullMethodName = "/gateway.v1.GatewayAdminService/GetGatewayVersion"
)

// GatewayAdminServiceClient is the client API for GatewayAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayAdminServiceClient interface {
	GetRouteSnapshot(ctx context.Context, in *GetRouteSnapshotRequest, opts ...grpc.CallOption) (*GetRouteSnapshotReply, error)
	ReloadRoutes(ctx context.Context, in *ReloadRoutesRequest, opts ...grpc.CallOption) (*ReloadRoutesReply, error)
	GetUpstreamHealth(ctx context.Context, in *GetUpstreamHealthRequest, opts ...grpc.CallOption) (*GetUpstreamHealthReply, error)
	GetGatewayVersion(ctx context.Context, in *GetGatewayVersionRequest, opts ...grpc.CallOption) (*GetGatewayVersionReply, error)
}

type gatewayAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayAdminServiceClient(cc grpc.ClientConnInterface) GatewayAdminServiceClient {
	return &gatewayAdminServiceClient{cc}
}

func (c *gatewayAdminServiceClient) GetRouteSnapshot(ctx context.Context, in *GetRouteSnapshotRequest, opts ...grpc.CallOption) (*GetRouteSnapshotReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRouteSnapshotReply)
	err := c.cc.Invoke(ctx, GatewayAdminService_GetRouteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAdminServiceClient) ReloadRoutes(ctx context.Context, in *ReloadRoutesRequest, opts ...grpc.CallOption) (*ReloadRoutesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadRoutesReply)
	err := c.cc.Invoke(ctx, GatewayAdminService_ReloadRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAdminServiceClient) GetUpstreamHealth(ctx context.Context, in *GetUpstreamHealthRequest, opts ...grpc.CallOption) (*GetUpstreamHealthReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUpstreamHealthReply)
	err := c.cc.Invoke(ctx, GatewayAdminService_GetUpstreamHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayAdminServiceClient) GetGatewayVersion(ctx context.Context, in *GetGatewayVersionRequest, opts ...grpc.CallOption) (*GetGatewayVersionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGatewayVersionReply)
	err := c.cc.Invoke(ctx, GatewayAdminService_GetGatewayVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayAdminServiceServer is the server API for GatewayAdminService service.
// All implementations must embed UnimplementedGatewayAdminServiceServer
// for forward compatibility.
type GatewayAdminServiceServer interface {
	GetRouteSnapshot(context.Context, *GetRouteSnapshotRequest) (*GetRouteSnapshotReply, error)
	ReloadRoutes(context.Context, *ReloadRoutesRequest) (*ReloadRoutesReply, error)
	GetUpstreamHealth(context.Context, *GetUpstreamHealthRequest) (*GetUpstreamHealthReply, error)
	GetGatewayVersion(context.Context, *GetGatewayVersionRequest) (*GetGatewayVersionReply, error)
	mustEmbedUnimplementedGatewayAdminServiceServer()
}

// UnimplementedGatewayAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayAdminServiceServer struct{}

func (UnimplementedGatewayAdminServiceServer) GetRouteSnapshot(context.Context, *GetRouteSnapshotRequest) (*GetRouteSnapshotReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRouteSnapshot not implemented")
}
func (UnimplementedGatewayAdminServiceServer) ReloadRoutes(context.Context, *ReloadRoutesRequest) (*ReloadRoutesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReloadRoutes not implemented")
}
func (UnimplementedGatewayAdminServiceServer) GetUpstreamHealth(context.Context, *GetUpstreamHealthRequest) (*GetUpstreamHealthReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUpstreamHealth not implemented")
}
func (UnimplementedGatewayAdminServiceServer) GetGatewayVersion(context.Context, *GetGatewayVersionRequest) (*GetGatewayVersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGatewayVersion not implemented")
}
func (UnimplementedGatewayAdminServiceServer) mustEmbedUnimplementedGatewayAdminServiceServer() {}
func (UnimplementedGatewayAdminServiceServer) testEmbeddedByValue()                             {}

// UnsafeGatewayAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayAdminServiceServer will
// result in compilation errors.
type UnsafeGatewayAdminServiceServer interface {
	mustEmbedUnimplementedGatewayAdminServiceServer()
}

func RegisterGatewayAdminServiceServer(s grpc.ServiceRegistrar, srv GatewayAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedGatewayAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayAdminService_ServiceDesc, srv)
}

func _GatewayAdminService_GetRouteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRouteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAdminServiceServer).GetRouteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAdminService_GetRouteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAdminServiceServer).GetRouteSnapshot(ctx, req.(*GetRouteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAdminService_ReloadRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAdminServiceServer).ReloadRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAdminService_ReloadRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAdminServiceServer).ReloadRoutes(ctx, req.(*ReloadRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAdminService_GetUpstreamHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUpstreamHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAdminServiceServer).GetUpstreamHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAdminService_GetUpstreamHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAdminServiceServer).GetUpstreamHealth(ctx, req.(*GetUpstreamHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayAdminService_GetGatewayVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGatewayVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayAdminServiceServer).GetGatewayVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayAdminService_GetGatewayVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayAdminServiceServer).GetGatewayVersion(ctx, req.(*GetGatewayVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayAdminService_ServiceDesc is the grpc.ServiceDesc for GatewayAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.v1.GatewayAdminService",
	HandlerType: (*GatewayAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRouteSnapshot",
			Handler:    _GatewayAdminService_GetRouteSnapshot_Handler,
		},
		{
			MethodName: "ReloadRoutes",
			Handler:    _GatewayAdminService_ReloadRoutes_Handler,
		},
		{
			MethodName: "GetUpstreamHealth",
			Handler:    _GatewayAdminService_GetUpstreamHealth_Handler,
		},
		{
			MethodName: "GetGatewayVersion",
			Handler:    _GatewayAdminService_GetGatewayVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/gateway.proto",
}
