// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v0.1.18
// - protoc             (unknown)
// source: gateway/v1/gateway.proto

package v1

import (
	context "context"
	http "github.com/aisphereio/kernel/transportx/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kernel package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationGatewayAdminServiceGetGatewayVersion = "/gateway.v1.GatewayAdminService/GetGatewayVersion"
const OperationGatewayAdminServiceGetRouteSnapshot = "/gateway.v1.GatewayAdminService/GetRouteSnapshot"
const OperationGatewayAdminServiceGetUpstreamHealth = "/gateway.v1.GatewayAdminService/GetUpstreamHealth"
const OperationGatewayAdminServiceReloadRoutes = "/gateway.v1.GatewayAdminService/ReloadRoutes"

type GatewayAdminServiceHTTPServer interface {
	GetGatewayVersion(context.Context, *GetGatewayVersionRequest) (*GetGatewayVersionReply, error)
	GetRouteSnapshot(context.Context, *GetRouteSnapshotRequest) (*GetRouteSnapshotReply, error)
	GetUpstreamHealth(context.Context, *GetUpstreamHealthRequest) (*GetUpstreamHealthReply, error)
	ReloadRoutes(context.Context, *ReloadRoutesRequest) (*ReloadRoutesReply, error)
}

func RegisterGatewayAdminServiceHTTPServer(s *http.Server, srv GatewayAdminServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/gateway/routes", _GatewayAdminService_GetRouteSnapshot0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/gateway/version", _GatewayAdminService_GetGatewayVersion0_HTTP_Handler(srv))
	r.Handle("GET", "/v1/gateway/upstreams/{service}", _GatewayAdminService_GetUpstreamHealth0_HTTP_Handler(srv))
	r.Handle("POST", "/v1/gateway/routes/reload", _GatewayAdminService_ReloadRoutes0_HTTP_Handler(srv))
}

func _GatewayAdminService_GetRouteSnapshot0_HTTP_Handler(srv GatewayAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRouteSnapshotRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayAdminServiceGetRouteSnapshot)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRouteSnapshot(ctx, req.(*GetRouteSnapshotRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRouteSnapshotReply)
		return ctx.Result(200, reply)
	}
}

func _GatewayAdminService_GetGatewayVersion0_HTTP_Handler(srv GatewayAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGatewayVersionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayAdminServiceGetGatewayVersion)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGatewayVersion(ctx, req.(*GetGatewayVersionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGatewayVersionReply)
		return ctx.Result(200, reply)
	}
}

func _GatewayAdminService_GetUpstreamHealth0_HTTP_Handler(srv GatewayAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUpstreamHealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayAdminServiceGetUpstreamHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUpstreamHealth(ctx, req.(*GetUpstreamHealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUpstreamHealthReply)
		return ctx.Result(200, reply)
	}
}

func _GatewayAdminService_ReloadRoutes0_HTTP_Handler(srv GatewayAdminServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReloadRoutesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := http.ValidateRequest(ctx, &in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayAdminServiceReloadRoutes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReloadRoutes(ctx, req.(*ReloadRoutesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReloadRoutesReply)
		return ctx.Result(200, reply)
	}
}

type GatewayAdminServiceHTTPClient interface {
	GetGatewayVersion(ctx context.Context, req *GetGatewayVersionRequest, opts ...http.CallOption) (rsp *GetGatewayVersionReply, err error)
	GetRouteSnapshot(ctx context.Context, req *GetRouteSnapshotRequest, opts ...http.CallOption) (rsp *GetRouteSnapshotReply, err error)
	GetUpstreamHealth(ctx context.Context, req *GetUpstreamHealthRequest, opts ...http.CallOption) (rsp *GetUpstreamHealthReply, err error)
	ReloadRoutes(ctx context.Context, req *ReloadRoutesRequest, opts ...http.CallOption) (rsp *ReloadRoutesReply, err error)
}

type GatewayAdminServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewGatewayAdminServiceHTTPClient(client *http.Client) GatewayAdminServiceHTTPClient {
	return &GatewayAdminServiceHTTPClientImpl{client}
}

func (c *GatewayAdminServiceHTTPClientImpl) GetGatewayVersion(ctx context.Context, in *GetGatewayVersionRequest, opts ...http.CallOption) (*GetGatewayVersionReply, error) {
	var out GetGatewayVersionReply
	pattern := "/v1/gateway/version"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGatewayAdminServiceGetGatewayVersion),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayAdminServiceHTTPClientImpl) GetRouteSnapshot(ctx context.Context, in *GetRouteSnapshotRequest, opts ...http.CallOption) (*GetRouteSnapshotReply, error) {
	var out GetRouteSnapshotReply
	pattern := "/v1/gateway/routes"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGatewayAdminServiceGetRouteSnapshot),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayAdminServiceHTTPClientImpl) GetUpstreamHealth(ctx context.Context, in *GetUpstreamHealthRequest, opts ...http.CallOption) (*GetUpstreamHealthReply, error) {
	var out GetUpstreamHealthReply
	pattern := "/v1/gateway/upstreams/{service}"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationGatewayAdminServiceGetUpstreamHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayAdminServiceHTTPClientImpl) ReloadRoutes(ctx context.Context, in *ReloadRoutesRequest, opts ...http.CallOption) (*ReloadRoutesReply, error) {
	var out ReloadRoutesReply
	pattern := "/v1/gateway/routes/reload"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationGatewayAdminServiceReloadRoutes),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
