// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel v0.1.18
// source: gateway/v1/gateway.proto

package v1

import (
	serverx "github.com/aisphereio/kernel/serverx"
)

// GatewayAdminServiceKernelModule returns the generated Kernel service module for gateway.v1.GatewayAdminService.
func GatewayAdminServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "gateway.admin-service",
		GatewayManifest:     GatewayAdminServiceGatewayManifest(),
		RequestInfoResolver: GatewayAdminServiceRequestInfoResolver,
		AccessResolver:      GatewayAdminServiceAccessResolver,
	}
}
