// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/v1/gateway.proto

package v1

import (
	_ "github.com/aisphereio/kernel/api/aisphere/access/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRouteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteSnapshotRequest) Reset() {
	*x = GetRouteSnapshotRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteSnapshotRequest) ProtoMessage() {}

func (x *GetRouteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetRouteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type GetRouteSnapshotReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      string                 `protobuf:"bytes,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	Routes        []*Route               `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	Warnings      []string               `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteSnapshotReply) Reset() {
	*x = GetRouteSnapshotReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteSnapshotReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteSnapshotReply) ProtoMessage() {}

func (x *GetRouteSnapshotReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteSnapshotReply.ProtoReflect.Descriptor instead.
func (*GetRouteSnapshotReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *GetRouteSnapshotReply) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GetRouteSnapshotReply) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GetRouteSnapshotReply) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *GetRouteSnapshotReply) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *GetRouteSnapshotReply) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ReloadRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	DryRun        bool                   `protobuf:"varint,3,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	Force         bool                   `protobuf:"varint,4,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRoutesRequest) Reset() {
	*x = ReloadRoutesRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRoutesRequest) ProtoMessage() {}

func (x *ReloadRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRoutesRequest.ProtoReflect.Descriptor instead.
func (*ReloadRoutesRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ReloadRoutesRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReloadRoutesRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReloadRoutesRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

func (x *ReloadRoutesRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type ReloadRoutesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteCount    int32                  `protobuf:"varint,1,opt,name=route_count,json=routeCount,proto3" json:"route_count,omitempty"`
	Revision      string                 `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Changed       bool                   `protobuf:"varint,3,opt,name=changed,proto3" json:"changed,omitempty"`
	Warnings      []string               `protobuf:"bytes,4,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadRoutesReply) Reset() {
	*x = ReloadRoutesReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadRoutesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadRoutesReply) ProtoMessage() {}

func (x *ReloadRoutesReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadRoutesReply.ProtoReflect.Descriptor instead.
func (*ReloadRoutesReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ReloadRoutesReply) GetRouteCount() int32 {
	if x != nil {
		return x.RouteCount
	}
	return 0
}

func (x *ReloadRoutesReply) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *ReloadRoutesReply) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *ReloadRoutesReply) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type GetUpstreamHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpstreamHealthRequest) Reset() {
	*x = GetUpstreamHealthRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpstreamHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpstreamHealthRequest) ProtoMessage() {}

func (x *GetUpstreamHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpstreamHealthRequest.ProtoReflect.Descriptor instead.
func (*GetUpstreamHealthRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetUpstreamHealthRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetUpstreamHealthRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetUpstreamHealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Endpoints     []*UpstreamEndpoint    `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUpstreamHealthReply) Reset() {
	*x = GetUpstreamHealthReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUpstreamHealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUpstreamHealthReply) ProtoMessage() {}

func (x *GetUpstreamHealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUpstreamHealthReply.ProtoReflect.Descriptor instead.
func (*GetUpstreamHealthReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetUpstreamHealthReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *GetUpstreamHealthReply) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetUpstreamHealthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetUpstreamHealthReply) GetEndpoints() []*UpstreamEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type GetGatewayVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayVersionRequest) Reset() {
	*x = GetGatewayVersionRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayVersionRequest) ProtoMessage() {}

func (x *GetGatewayVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayVersionRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayVersionRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

type GetGatewayVersionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayVersionReply) Reset() {
	*x = GetGatewayVersionReply{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayVersionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayVersionReply) ProtoMessage() {}

func (x *GetGatewayVersionReply) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayVersionReply.ProtoReflect.Descriptor instead.
func (*GetGatewayVersionReply) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetGatewayVersionReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetGatewayVersionReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Exposure      string                 `protobuf:"bytes,5,opt,name=exposure,proto3" json:"exposure,omitempty"`
	AuthnMode     string                 `protobuf:"bytes,6,opt,name=authn_mode,json=authnMode,proto3" json:"authn_mode,omitempty"`
	Upstream      *Upstream              `protobuf:"bytes,7,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *Route) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Route) GetExposure() string {
	if x != nil {
		return x.Exposure
	}
	return ""
}

func (x *Route) GetAuthnMode() string {
	if x != nil {
		return x.AuthnMode
	}
	return ""
}

func (x *Route) GetUpstream() *Upstream {
	if x != nil {
		return x.Upstream
	}
	return nil
}

func (x *Route) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Upstream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Operation     string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Upstream) Reset() {
	*x = Upstream{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Upstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Upstream) ProtoMessage() {}

func (x *Upstream) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Upstream.ProtoReflect.Descriptor instead.
func (*Upstream) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *Upstream) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Upstream) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Upstream) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Upstream) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Upstream) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

type UpstreamEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpstreamEndpoint) Reset() {
	*x = UpstreamEndpoint{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpstreamEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpstreamEndpoint) ProtoMessage() {}

func (x *UpstreamEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpstreamEndpoint.ProtoReflect.Descriptor instead.
func (*UpstreamEndpoint) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *UpstreamEndpoint) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UpstreamEndpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpstreamEndpoint) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpstreamEndpoint) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\n" +
	"gateway.v1\x1a\x1faisphere/access/v1/access.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n" +
	"\x17GetRouteSnapshotRequest\"\xd1\x01\n" +
	"\x15GetRouteSnapshotReply\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\tR\brevision\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12=\n" +
	"\fgenerated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12)\n" +
	"\x06routes\x18\x04 \x03(\v2\x11.gateway.v1.RouteR\x06routes\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings\"z\n" +
	"\x13ReloadRoutesRequest\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x17\n" +
	"\adry_run\x18\x03 \x01(\bR\x06dryRun\x12\x14\n" +
	"\x05force\x18\x04 \x01(\bR\x05force\"\x86\x01\n" +
	"\x11ReloadRoutesReply\x12\x1f\n" +
	"\vroute_count\x18\x01 \x01(\x05R\n" +
	"routeCount\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x18\n" +
	"\achanged\x18\x03 \x01(\bR\achanged\x12\x1a\n" +
	"\bwarnings\x18\x04 \x03(\tR\bwarnings\"R\n" +
	"\x18GetUpstreamHealthRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xa4\x01\n" +
	"\x16GetUpstreamHealthReply\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12:\n" +
	"\tendpoints\x18\x04 \x03(\v2\x1c.gateway.v1.UpstreamEndpointR\tendpoints\"\x1a\n" +
	"\x18GetGatewayVersionRequest\"F\n" +
	"\x16GetGatewayVersionReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xb6\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1a\n" +
	"\bexposure\x18\x05 \x01(\tR\bexposure\x12\x1d\n" +
	"\n" +
	"authn_mode\x18\x06 \x01(\tR\tauthnMode\x120\n" +
	"\bupstream\x18\a \x01(\v2\x14.gateway.v1.UpstreamR\bupstream\x125\n" +
	"\x06labels\x18\b \x03(\v2\x1d.gateway.v1.Route.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x01\n" +
	"\bUpstream\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\"n\n" +
	"\x10UpstreamEndpoint\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason2\xf3\x06\n" +
	"\x13GatewayAdminService\x12\xc9\x01\n" +
	"\x10GetRouteSnapshot\x12#.gateway.v1.GetRouteSnapshotRequest\x1a!.gateway.v1.GetRouteSnapshotReply\"m\x92\xf4\x18O\b\x05\x12)\n" +
	"\x04read\x12\x0egateway:routes\x1a\x0fgateway-service \x01\x1a \b\x01\x12\x17gateway.routes.snapshot\x1a\x03low\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/gateway/routes\x12\xca\x01\n" +
	"\fReloadRoutes\x12\x1f.gateway.v1.ReloadRoutesRequest\x1a\x1d.gateway.v1.ReloadRoutesReply\"z\x92\xf4\x18R\b\x05\x12+\n" +
	"\x06reload\x12\x0egateway:routes\x1a\x0fgateway-service \x01\x1a!\b\x01\x12\x15gateway.routes.reload\x1a\x06medium\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/gateway/routes/reload\x12\xe6\x01\n" +
	"\x11GetUpstreamHealth\x12$.gateway.v1.GetUpstreamHealthRequest\x1a\".gateway.v1.GetUpstreamHealthReply\"\x86\x01\x92\xf4\x18[\b\x05\x125\n" +
	"\x04read\x12\x1agateway:upstream:{service}\x1a\x0fgateway-service \x01\x1a \b\x01\x12\x17gateway.upstream.health\x1a\x03low\x82\xd3\xe4\x93\x02!\x12\x1f/v1/gateway/upstreams/{service}\x12\xd9\x01\n" +
	"\x11GetGatewayVersion\x12$.gateway.v1.GetGatewayVersionRequest\x1a\".gateway.v1.GetGatewayVersionReply\"z\x92\xf4\x18[\b\x04\x1a\x18\b\x01\x12\x0fgateway.version\x1a\x03low2=Gateway version is limited to internal control-plane callers.\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/gateway/versionB:Z8github.com/aisphereio/aisphere-gateway/api/gateway/v1;v1b\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(*GetRouteSnapshotRequest)(nil),  // 0: gateway.v1.GetRouteSnapshotRequest
	(*GetRouteSnapshotReply)(nil),    // 1: gateway.v1.GetRouteSnapshotReply
	(*ReloadRoutesRequest)(nil),      // 2: gateway.v1.ReloadRoutesRequest
	(*ReloadRoutesReply)(nil),        // 3: gateway.v1.ReloadRoutesReply
	(*GetUpstreamHealthRequest)(nil), // 4: gateway.v1.GetUpstreamHealthRequest
	(*GetUpstreamHealthReply)(nil),   // 5: gateway.v1.GetUpstreamHealthReply
	(*GetGatewayVersionRequest)(nil), // 6: gateway.v1.GetGatewayVersionRequest
	(*GetGatewayVersionReply)(nil),   // 7: gateway.v1.GetGatewayVersionReply
	(*Route)(nil),                    // 8: gateway.v1.Route
	(*Upstream)(nil),                 // 9: gateway.v1.Upstream
	(*UpstreamEndpoint)(nil),         // 10: gateway.v1.UpstreamEndpoint
	nil,                              // 11: gateway.v1.Route.LabelsEntry
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	12, // 0: gateway.v1.GetRouteSnapshotReply.generated_at:type_name -> google.protobuf.Timestamp
	8,  // 1: gateway.v1.GetRouteSnapshotReply.routes:type_name -> gateway.v1.Route
	10, // 2: gateway.v1.GetUpstreamHealthReply.endpoints:type_name -> gateway.v1.UpstreamEndpoint
	9,  // 3: gateway.v1.Route.upstream:type_name -> gateway.v1.Upstream
	11, // 4: gateway.v1.Route.labels:type_name -> gateway.v1.Route.LabelsEntry
	0,  // 5: gateway.v1.GatewayAdminService.GetRouteSnapshot:input_type -> gateway.v1.GetRouteSnapshotRequest
	2,  // 6: gateway.v1.GatewayAdminService.ReloadRoutes:input_type -> gateway.v1.ReloadRoutesRequest
	4,  // 7: gateway.v1.GatewayAdminService.GetUpstreamHealth:input_type -> gateway.v1.GetUpstreamHealthRequest
	6,  // 8: gateway.v1.GatewayAdminService.GetGatewayVersion:input_type -> gateway.v1.GetGatewayVersionRequest
	1,  // 9: gateway.v1.GatewayAdminService.GetRouteSnapshot:output_type -> gateway.v1.GetRouteSnapshotReply
	3,  // 10: gateway.v1.GatewayAdminService.ReloadRoutes:output_type -> gateway.v1.ReloadRoutesReply
	5,  // 11: gateway.v1.GatewayAdminService.GetUpstreamHealth:output_type -> gateway.v1.GetUpstreamHealthReply
	7,  // 12: gateway.v1.GatewayAdminService.GetGatewayVersion:output_type -> gateway.v1.GetGatewayVersionReply
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
