// Code generated by protoc-gen-go-gateway. DO NOT EDIT.
// versions:
// - protoc-gen-go-gateway dev
// source: gateway/v1/gateway.proto

package v1

import (
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	gatewayx "github.com/aisphereio/kernel/gatewayx"
)

// GatewayAdminServiceGatewayManifest returns the generated Gateway route manifest for gateway.v1.GatewayAdminService.
func GatewayAdminServiceGatewayManifest() gatewayx.Manifest {
	return gatewayx.Manifest{
		Service:   "gateway.admin-service",
		Namespace: "aisphere",
		Routes: []gatewayx.GatewayRoute{
			{
				ID:       "gateway.admin.get.route.snapshot",
				Method:   "GET",
				Path:     "/v1/gateway/routes",
				Upstream: gatewayx.UpstreamRef{Service: "gateway-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/gateway.v1.GatewayAdminService/GetRouteSnapshot"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_SYSTEM, AuthnMode: gatewayx.AuthnModeNone, ForwardAuthorization: false},
			},
			{
				ID:       "gateway.admin.reload.routes",
				Method:   "POST",
				Path:     "/v1/gateway/routes/reload",
				Upstream: gatewayx.UpstreamRef{Service: "gateway-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/gateway.v1.GatewayAdminService/ReloadRoutes"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_SYSTEM, AuthnMode: gatewayx.AuthnModeNone, ForwardAuthorization: false},
			},
			{
				ID:       "gateway.admin.get.upstream.health",
				Method:   "GET",
				Path:     "/v1/gateway/upstreams/{service}",
				Upstream: gatewayx.UpstreamRef{Service: "gateway-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/gateway.v1.GatewayAdminService/GetUpstreamHealth"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_SYSTEM, AuthnMode: gatewayx.AuthnModeNone, ForwardAuthorization: false},
			},
			{
				ID:       "gateway.admin.get.gateway.version",
				Method:   "GET",
				Path:     "/v1/gateway/version",
				Upstream: gatewayx.UpstreamRef{Service: "gateway.admin-service", Namespace: "aisphere", Protocol: "grpc", Operation: "/gateway.v1.GatewayAdminService/GetGatewayVersion"},
				Gateway:  gatewayx.GatewayPolicy{Exposure: v1.Exposure_INTERNAL, AuthnMode: gatewayx.AuthnModePassive, ForwardAuthorization: true},
			},
		},
	}
}

// GatewayAdminServiceGatewayBindGetRouteSnapshot binds the matched HTTP Gateway request to the gRPC request for /gateway.v1.GatewayAdminService/GetRouteSnapshot.
func GatewayAdminServiceGatewayBindGetRouteSnapshot(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetRouteSnapshotRequest, error) {
	out := &GetRouteSnapshotRequest{}
	if v, ok := req.Body.(*GetRouteSnapshotRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetRouteSnapshotRequest); ok {
		out = &v
	}
	return out, nil
}

// GatewayAdminServiceGatewayBindReloadRoutes binds the matched HTTP Gateway request to the gRPC request for /gateway.v1.GatewayAdminService/ReloadRoutes.
func GatewayAdminServiceGatewayBindReloadRoutes(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*ReloadRoutesRequest, error) {
	out := &ReloadRoutesRequest{}
	if v, ok := req.Body.(*ReloadRoutesRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(ReloadRoutesRequest); ok {
		out = &v
	}
	return out, nil
}

// GatewayAdminServiceGatewayBindGetUpstreamHealth binds the matched HTTP Gateway request to the gRPC request for /gateway.v1.GatewayAdminService/GetUpstreamHealth.
func GatewayAdminServiceGatewayBindGetUpstreamHealth(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetUpstreamHealthRequest, error) {
	out := &GetUpstreamHealthRequest{}
	if v, ok := req.Body.(*GetUpstreamHealthRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetUpstreamHealthRequest); ok {
		out = &v
	}
	if v := match.Params["service"]; v != "" {
		out.Service = v
	}
	return out, nil
}

// GatewayAdminServiceGatewayBindGetGatewayVersion binds the matched HTTP Gateway request to the gRPC request for /gateway.v1.GatewayAdminService/GetGatewayVersion.
func GatewayAdminServiceGatewayBindGetGatewayVersion(req gatewayx.DispatchRequest, match gatewayx.RouteMatch) (*GetGatewayVersionRequest, error) {
	out := &GetGatewayVersionRequest{}
	if v, ok := req.Body.(*GetGatewayVersionRequest); ok && v != nil {
		out = v
	}
	if v, ok := req.Body.(GetGatewayVersionRequest); ok {
		out = &v
	}
	return out, nil
}

// RegisterGatewayAdminServiceGatewayInvokers registers generated Gateway -> gRPC operation invokers for gateway.v1.GatewayAdminService.
func RegisterGatewayAdminServiceGatewayInvokers(registry *gatewayx.InvokerRegistry, client GatewayAdminServiceClient) error {
	if err := registry.Register("/gateway.v1.GatewayAdminService/GetRouteSnapshot", gatewayx.GRPCUnaryInvoker(GatewayAdminServiceGatewayBindGetRouteSnapshot, client.GetRouteSnapshot)); err != nil {
		return err
	}
	if err := registry.Register("/gateway.v1.GatewayAdminService/ReloadRoutes", gatewayx.GRPCUnaryInvoker(GatewayAdminServiceGatewayBindReloadRoutes, client.ReloadRoutes)); err != nil {
		return err
	}
	if err := registry.Register("/gateway.v1.GatewayAdminService/GetUpstreamHealth", gatewayx.GRPCUnaryInvoker(GatewayAdminServiceGatewayBindGetUpstreamHealth, client.GetUpstreamHealth)); err != nil {
		return err
	}
	if err := registry.Register("/gateway.v1.GatewayAdminService/GetGatewayVersion", gatewayx.GRPCUnaryInvoker(GatewayAdminServiceGatewayBindGetGatewayVersion, client.GetGatewayVersion)); err != nil {
		return err
	}
	return nil
}
