// Code generated by protoc-gen-go-kernel. DO NOT EDIT.
// versions:
// - protoc-gen-go-kernel dev
// source: gateway/v1/gateway.proto

package v1

import (
	context "context"
	accessx "github.com/aisphereio/kernel/accessx"
	v1 "github.com/aisphereio/kernel/api/aisphere/access/v1"
	authz "github.com/aisphereio/kernel/authz"
	requestx "github.com/aisphereio/kernel/requestx"
	serverx "github.com/aisphereio/kernel/serverx"
)

// GatewayAdminServiceKernelModule returns the generated Kernel service module for gateway.v1.GatewayAdminService.
func GatewayAdminServiceKernelModule() serverx.ServiceModule {
	return serverx.ServiceModule{
		Name:                "gateway.admin-service",
		GatewayManifest:     GatewayAdminServiceGatewayManifest(),
		RequestInfoResolver: GatewayAdminServiceKernelRequestInfoResolver,
		AccessResolver:      GatewayAdminServiceKernelAccessResolver,
	}
}

var GatewayAdminServiceKernelAuthzRules = authz.Rules{
	"/gateway.v1.GatewayAdminService/GetRouteSnapshot": {
		Service:    "gateway.v1.GatewayAdminService",
		Method:     "GetRouteSnapshot",
		FullMethod: "/gateway.v1.GatewayAdminService/GetRouteSnapshot",
		Action:     "read",
		Resource:   "gateway:routes",
		Audience:   "gateway-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "gateway.routes.snapshot",
		AuditRisk:  "low",
	},
	"/gateway.v1.GatewayAdminService/ReloadRoutes": {
		Service:    "gateway.v1.GatewayAdminService",
		Method:     "ReloadRoutes",
		FullMethod: "/gateway.v1.GatewayAdminService/ReloadRoutes",
		Action:     "reload",
		Resource:   "gateway:routes",
		Audience:   "gateway-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "gateway.routes.reload",
		AuditRisk:  "medium",
	},
	"/gateway.v1.GatewayAdminService/GetUpstreamHealth": {
		Service:    "gateway.v1.GatewayAdminService",
		Method:     "GetUpstreamHealth",
		FullMethod: "/gateway.v1.GatewayAdminService/GetUpstreamHealth",
		Action:     "read",
		Resource:   "gateway:upstream:{service}",
		Audience:   "gateway-service",
		Mode:       authz.RuleMode("CHECK_ONLY"),
		AuditEvent: "gateway.upstream.health",
		AuditRisk:  "low",
	},
}

// GatewayAdminServiceKernelRequestInfoResolver maps proto access policy into requestx.Info for serverx modules.
func GatewayAdminServiceKernelRequestInfoResolver(ctx context.Context, operation string, req any) (requestx.Info, bool, error) {
	_ = ctx
	_ = req
	switch _GatewayAdminServiceKernelNormalizeOperation(operation) {
	case "/gateway.v1.GatewayAdminService/GetRouteSnapshot":
		info := requestx.Info{
			Service:       "gateway.v1.GatewayAdminService",
			Method:        "GetRouteSnapshot",
			Operation:     "/gateway.v1.GatewayAdminService/GetRouteSnapshot",
			Exposure:      v1.Exposure_SYSTEM,
			Action:        "read",
			Resource:      "gateway:routes",
			TargetService: "gateway-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "gateway.routes.snapshot"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/gateway.v1.GatewayAdminService/ReloadRoutes":
		info := requestx.Info{
			Service:       "gateway.v1.GatewayAdminService",
			Method:        "ReloadRoutes",
			Operation:     "/gateway.v1.GatewayAdminService/ReloadRoutes",
			Exposure:      v1.Exposure_SYSTEM,
			Action:        "reload",
			Resource:      "gateway:routes",
			TargetService: "gateway-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "gateway.routes.reload"
		info.Labels["audit_risk"] = "medium"
		return info.Normalize(), true, nil
	case "/gateway.v1.GatewayAdminService/GetUpstreamHealth":
		info := requestx.Info{
			Service:       "gateway.v1.GatewayAdminService",
			Method:        "GetUpstreamHealth",
			Operation:     "/gateway.v1.GatewayAdminService/GetUpstreamHealth",
			Exposure:      v1.Exposure_SYSTEM,
			Action:        "read",
			Resource:      "gateway:upstream:{service}",
			TargetService: "gateway-service",
			Labels:        map[string]string{},
		}
		info.Labels["authz_mode"] = "CHECK_ONLY"
		info.Labels["audit_event"] = "gateway.upstream.health"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	case "/gateway.v1.GatewayAdminService/GetGatewayVersion":
		info := requestx.Info{
			Service:   "gateway.v1.GatewayAdminService",
			Method:    "GetGatewayVersion",
			Operation: "/gateway.v1.GatewayAdminService/GetGatewayVersion",
			Exposure:  v1.Exposure_INTERNAL,
			Labels:    map[string]string{},
		}
		info.Labels["authz_mode"] = "UNSPECIFIED"
		info.Labels["audit_event"] = "gateway.version"
		info.Labels["audit_risk"] = "low"
		return info.Normalize(), true, nil
	default:
		return requestx.Info{}, false, nil
	}
}

// GatewayAdminServiceKernelAccessResolver maps proto authz policy into accessx.Check for serverx modules.
func GatewayAdminServiceKernelAccessResolver(ctx context.Context, operation string, req any) (accessx.Check, bool, error) {
	rule, ok := GatewayAdminServiceKernelAuthzRules[_GatewayAdminServiceKernelNormalizeOperation(operation)]
	if !ok || rule.Action == "" {
		return accessx.Check{}, false, nil
	}
	resource, err := (authz.RuleResolver{}).ResolveResource(rule, req)
	if err != nil {
		return accessx.Check{}, true, err
	}
	_ = ctx
	check := accessx.Check{
		Permission:  rule.Action,
		Resource:    resource,
		AuditAction: rule.AuditEvent,
		Metadata:    map[string]any{"authz_rule": rule.FullMethod, "authz_mode": string(rule.Mode)},
	}
	if check.AuditAction == "" {
		check.AuditAction = rule.Action
	}
	return check, true, nil
}

func _GatewayAdminServiceKernelNormalizeOperation(operation string) string {
	switch operation {
	case "GetRouteSnapshot", "gateway.v1.GatewayAdminService/GetRouteSnapshot":
		return "/gateway.v1.GatewayAdminService/GetRouteSnapshot"
	case "ReloadRoutes", "gateway.v1.GatewayAdminService/ReloadRoutes":
		return "/gateway.v1.GatewayAdminService/ReloadRoutes"
	case "GetUpstreamHealth", "gateway.v1.GatewayAdminService/GetUpstreamHealth":
		return "/gateway.v1.GatewayAdminService/GetUpstreamHealth"
	case "GetGatewayVersion", "gateway.v1.GatewayAdminService/GetGatewayVersion":
		return "/gateway.v1.GatewayAdminService/GetGatewayVersion"
	default:
		return operation
	}
}
